apiVersion: v1
entries:
  subchart-test:
  - apiVersion: v2
    appVersion: 1.23-alpine
    created: "2022-12-09T16:30:27.587962+09:00"
    description: A Helm chart for Kubernetes
    digest: 655996bce4318bfe0fa8bbb1439cd2c9f83ca5abee8d233bc49d2d6a6733fb75
    name: subchart-test
    type: application
    urls:
    - https://seodea.github.io/helm-package/charts/main/subchart-test-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.23-alpine
    created: "2022-12-09T16:30:27.587598+09:00"
    description: A Helm chart for Kubernetes
    digest: f3b35b5b7d6e1fc99404940ec25a32fbe481249aa2d589e578f460332feaaf75
    name: subchart-test
    type: application
    urls:
    - https://seodea.github.io/helm-package/charts/main/subchart-test-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-09T16:30:27.586976+09:00"
