apiVersion: v1
entries:
  subchart-test:
  - apiVersion: v2
    appVersion: 1.23-alpine
    created: "2022-12-09T12:29:35.284276+09:00"
    description: A Helm chart for Kubernetes
    digest: a876388d3cfc6ac7ea2edbe51eecdda7504a8de53c2ba7b15249f95b80041919
    name: subchart-test
    type: application
    urls:
    - https://seodea.github.io/helm-package/charts/main/subchart-test-0.2.0.tgz
    version: 0.1.0
generated: "2022-12-09T12:29:35.282007+09:00"
