apiVersion: v1
entries:
  subchart-test:
  - apiVersion: v1
    appVersion: 1.23-alpine
    created: "2022-12-16T10:15:52.469685+09:00"
    description: Project template Helm chart for Kubernetes
    digest: 280bba3f72f55c7a6a839a711f8c0092311625935ab9513f04d24f2f33a6dfa7
    name: subchart-test
    type: application
    urls:
    - https://seodea.github.io/helm-package/charts/main/subchart-test-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 1.23-alpine
    created: "2022-12-16T10:15:52.469224+09:00"
    description: Project template Helm chart for Kubernetes
    digest: f474962e0099211c4243054e6c5dc356b18114f1876dffcd759e540fec8dac74
    name: subchart-test
    type: application
    urls:
    - https://seodea.github.io/helm-package/charts/main/subchart-test-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-16T10:15:52.468613+09:00"
