apiVersion: v1
entries:
  subchart-test:
  - apiVersion: v2
    appVersion: 1.23-alpine
    created: "2022-12-09T16:33:21.126477+09:00"
    description: A Helm chart for Kubernetes
    digest: dc341f37218f09b53408c24bbcb2f80347a9378a7e7bda6d2ca3a47cf59e936b
    name: subchart-test
    type: application
    urls:
    - https://seodea.github.io/helm-package/charts/main/subchart-test-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-09T16:33:21.121912+09:00"
